Feature/create product order dish entities
gmzjohn/delicias-del-norte pull request #4
Opened 2023-01-23 20:24 UTC by gmzjohn

Create entities for product, dish, and order

2023-01-23 22:55 UTC, gmzjohn commented
So since all properties are private I think we can implement the constructor to set the properties there and also implement a getter for each property, example:

![image](https://user-images.githubusercontent.com/20670269/214170826-63d846dd-219d-4c6b-a6f5-52bfc0a34114.png)

2023-01-23 23:01 UTC, reynoldmorel commented
> So since all properties are private I think we can implement the constructor to set the properties there and also implement a getter for each property, example:
> 
> ![image](https://user-images.githubusercontent.com/20670269/214170826-63d846dd-219d-4c6b-a6f5-52bfc0a34114.png)

Why not just using `public` variables?

2023-01-24 20:10 UTC, reynoldmorel commented
> etters needed that way? Or we are going to leave it for readability?

you don't need getters that way

2023-01-24 20:25 UTC, gmzjohn commented
> > etters needed that way? Or we are going to leave it for readability?
> 
> 
> 
> you don't need getters that way

How about the constructors? I believe they are needed right?

2023-01-24 21:03 UTC, reynoldmorel commented
> > > etters needed that way? Or we are going to leave it for readability?
> > 
> > 
> > you don't need getters that way
> 
> How about the constructors? I believe they are needed right?

yes they are

2023-02-01 00:44 UTC, reynoldmorel requested changes

2023-02-01 00:44 UTC, reynoldmorel commented on entities/Dish.js
> +    id; // int
I think all these properties here are not necessary just leave the constructor definition

2023-02-06 16:14 UTC, closed without merging